import math
import re
from typing import Any

import numpy as np
from sentence_transformers import CrossEncoder, SentenceTransformer


class CitationVerifier:
    """
    Verifies citations generated by the model against the retrieved chunks.
    """

    _citation_group_pattern = re.compile(r"((?:\[\d+\])+)")
    _citation_pattern = re.compile(r"\[(\d+)\]")
    _number_pattern = re.compile(r"\b\d+(?:\.\d+)?\b")
    _date_pattern = re.compile(
        r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|"
        r"Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?|"
        r"\d{1,2}[/-]\d{1,2}[/-]\d{2,4})\b",
        re.IGNORECASE,
    )
    _stopwords = {
        "the",
        "and",
        "or",
        "of",
        "to",
        "a",
        "an",
        "in",
        "on",
        "for",
        "with",
        "by",
        "from",
        "that",
        "this",
        "these",
        "those",
        "is",
        "are",
        "was",
        "were",
        "it",
        "its",
        "as",
        "at",
        "be",
        "has",
        "have",
        "will",
        "may",
        "should",
        "can",
        "must",
        "shall",
        "do",
        "does",
        "did",
        "not",
        "no",
        "if",
        "than",
        "then",
        "also",
        "such",
        "more",
        "most",
        "between",
        "when",
        "while",
        "which",
        "their",
        "they",
        "them",
        "there",
        "here",
        "about",
        "into",
        "over",
        "under",
    }

    def __init__(
        self,
        crossencoder_model: str = "BAAI/bge-reranker-base",
        embedding_model: str = "all-MiniLM-L6-v2",
    ):
        self.crossencoder = CrossEncoder(crossencoder_model)
        self.embedder = SentenceTransformer(embedding_model)

    def _normalize_text(self, text: str) -> str:
        return re.sub(r"\s+", " ", text.strip().lower())

    def _extract_numbers(self, text: str) -> set[str]:
        return set(self._number_pattern.findall(text))

    def _extract_dates(self, text: str) -> set[str]:
        return {match.group(0).lower() for match in self._date_pattern.finditer(text)}

    def _keywords(self, text: str) -> set[str]:
        words = re.findall(r"\b[a-z]{3,}\b", text.lower())
        return {word for word in words if word not in self._stopwords}

    def _cosine_similarity(self, vector_a: np.ndarray, vector_b: np.ndarray) -> float:
        if vector_a.size == 0 or vector_b.size == 0:
            return 0.0
        score = float(
            np.dot(vector_a, vector_b)
            / (np.linalg.norm(vector_a) * np.linalg.norm(vector_b))
        )
        return max(0.0, min(1.0, score))

    def _normalize_cross_score(self, score: float) -> float:
        try:
            return 1.0 / (1.0 + math.exp(-score))
        except OverflowError:
            return 0.0 if score < 0 else 1.0

    def extract_citation_groups(self, answer: str) -> list[dict[str, Any]]:
        groups: list[dict[str, Any]] = []
        for match in self._citation_group_pattern.finditer(answer):
            citation_text = match.group(1)
            ids = [
                int(value) for value in self._citation_pattern.findall(citation_text)
            ]
            if not ids:
                continue

            previous_boundary = max(
                answer.rfind(".", 0, match.start(1)),
                answer.rfind("?", 0, match.start(1)),
                answer.rfind("!", 0, match.start(1)),
            )
            citation_prefix = (
                answer[previous_boundary + 1 : match.start(1)]
                if previous_boundary >= 0
                else ""
            )

            if previous_boundary >= 0 and citation_prefix.strip() == "":
                previous_previous = max(
                    answer.rfind(".", 0, previous_boundary),
                    answer.rfind("?", 0, previous_boundary),
                    answer.rfind("!", 0, previous_boundary),
                )
                sentence_start = previous_previous + 1 if previous_previous >= 0 else 0
                sentence_end = previous_boundary + 1
            else:
                sentence_start = previous_boundary + 1 if previous_boundary >= 0 else 0
                next_period = answer.find(".", match.end(1))
                next_question = answer.find("?", match.end(1))
                next_exclamation = answer.find("!", match.end(1))
                next_boundary_candidates = [
                    pos
                    for pos in (next_period, next_question, next_exclamation)
                    if pos >= 0
                ]
                sentence_end = (
                    min(next_boundary_candidates) + 1
                    if next_boundary_candidates
                    else len(answer)
                )

            sentence = answer[sentence_start:sentence_end].strip()
            groups.append(
                {
                    "citation_ids": ids,
                    "sentence": sentence,
                    "position": match.start(1),
                    "citation_text": citation_text,
                }
            )
        return groups

    def _embed(self, text: str) -> np.ndarray:
        embedding = self.embedder.encode(text, convert_to_numpy=True)
        norm = np.linalg.norm(embedding)
        return embedding / norm if norm else embedding

    def _semantic_metrics(self, sentence: str, chunk_text: str) -> dict[str, float]:
        sentence_norm = self._normalize_text(sentence)
        chunk_norm = self._normalize_text(chunk_text)
        cross_score = self.crossencoder.predict([(sentence_norm, chunk_norm)])[0]
        embedding_similarity = self._cosine_similarity(
            self._embed(sentence_norm), self._embed(chunk_norm)
        )
        return {
            "cross_encoder": self._normalize_cross_score(cross_score),
            "embedding": embedding_similarity,
        }

    def _keyword_overlap(self, sentence: str, chunk_text: str) -> float:
        sentence_keywords = self._keywords(sentence)
        chunk_keywords = self._keywords(chunk_text)
        if not sentence_keywords:
            return 0.0
        overlap = sentence_keywords.intersection(chunk_keywords)
        return len(overlap) / len(sentence_keywords)

    def _numeric_overlap(self, sentence: str, chunk_text: str) -> float:
        sentence_numbers = self._extract_numbers(sentence)
        if not sentence_numbers:
            return 1.0
        chunk_numbers = self._extract_numbers(chunk_text)
        matched = sum(1 for number in sentence_numbers if number in chunk_numbers)
        return matched / len(sentence_numbers)

    def _date_overlap(self, sentence: str, chunk_text: str) -> float:
        sentence_dates = self._extract_dates(sentence)
        if not sentence_dates:
            return 1.0
        chunk_dates = self._extract_dates(chunk_text)
        matched = sum(1 for date in sentence_dates if date in chunk_dates)
        return matched / len(sentence_dates)

    def _score_claim(self, sentence: str, chunk_text: str) -> float:
        metrics = self._semantic_metrics(sentence, chunk_text)
        keyword_overlap = self._keyword_overlap(sentence, chunk_text)
        numeric_overlap = self._numeric_overlap(sentence, chunk_text)
        date_overlap = self._date_overlap(sentence, chunk_text)

        # Weighted score blends semantic and keyword evidence, with exact numeric/date checks
        score = (
            metrics["cross_encoder"] * 0.4
            + metrics["embedding"] * 0.35
            + keyword_overlap * 0.15
            + min(numeric_overlap, date_overlap) * 0.1
        )
        return max(0.0, min(1.0, score))

    def _confidence_level(self, score: float) -> str:
        if score >= 0.8:
            return "High"
        if score >= 0.55:
            return "Medium"
        return "Low"

    def verify(
        self,
        answer: str,
        citation_map: dict[int, dict],
    ) -> dict[str, Any]:
        citation_groups = self.extract_citation_groups(answer)
        citations: list[dict[str, Any]] = []
        invalid_ids: set[int] = set()
        unsupported_claims: list[dict[str, Any]] = []

        for group in citation_groups:
            for citation_id in group["citation_ids"]:
                if citation_id not in citation_map:
                    invalid_ids.add(citation_id)
                    unsupported_claims.append(
                        {
                            "citation_id": citation_id,
                            "sentence": group["sentence"],
                            "reason": "Citation number does not exist in the retrieved context.",
                        }
                    )
                    continue

                chunk = citation_map[citation_id]
                support_score = self._score_claim(group["sentence"], chunk["content"])
                valid = support_score >= 0.5
                if not valid:
                    invalid_ids.add(citation_id)
                    unsupported_claims.append(
                        {
                            "citation_id": citation_id,
                            "sentence": group["sentence"],
                            "reason": "The cited chunk does not sufficiently support the statement.",
                            "score": support_score,
                        }
                    )

                citations.append(
                    {
                        "id": citation_id,
                        "source": chunk["source"],
                        "page": chunk["page"],
                        "chunk_id": chunk["chunk_id"],
                        # Required by QueryResponse
                        "content": chunk["content"],
                        # Detailed citation fields
                        "chunk_text": chunk["content"],
                        "sentence": group["sentence"],
                        "position": group["position"],
                        "confidence": support_score,
                        "valid": valid,
                        "confidence_level": self._confidence_level(support_score),
                    }
                )

        valid_ids = {citation["id"] for citation in citations if citation["valid"]}
        total_citations = len(valid_ids | invalid_ids)
        valid_count = len(valid_ids)
        invalid_count = len(invalid_ids)
        coverage = (
            0 if total_citations == 0 else int((valid_count / total_citations) * 100)
        )
        citation_confidence = sum(
            citation["confidence"] for citation in citations if citation["valid"]
        ) / max(valid_count, 1)

        citation_confidence = max(0.0, min(1.0, citation_confidence))
        confidence_level = self._confidence_level(citation_confidence)

        citation_summary = {
            "valid": valid_count,
            "invalid": invalid_count,
            "coverage": coverage,
            "confidence_level": confidence_level,
        }

        logger = {
            "citation_groups": citation_groups,
            "citation_map": citation_map,
            "unsupported_claims": unsupported_claims,
            "summary": citation_summary,
        }

        return {
            "citations": citations,
            "invalid_ids": invalid_ids,
            "citation_summary": citation_summary,
            "citation_confidence": citation_confidence,
            "unsupported_claims": unsupported_claims,
            "verification_log": logger,
        }
